### ISSUE TITLE
Standard I/O library

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/asteria#93]
1. There are two standard streams: the _standard input_ stream and the _standard output_ stream. All input operations apply to _standard input_. All output operations apply to _standard output_.
2. Each stream may be _byte-oriented_ or _text-oriented_. A _byte-oriented_ stream consists of a sequence of bytes. A _text-oriented_ stream consists of a sequence of _UTF code points_ encoded in **UTF-8**.
3. Upon start, both streams are neither _byte-oriented_ or _text-oriented_. A byte operation that has been applied to a stream makes the stream _byte-oriented_. A text operation that has been applied to a stream makes the stream _text-oriented_.
4. If a byte operation is applied to a _text-oriented_ stream or vice versa, the operation fails.
5. Successful byte input operations shall not return partial UTF code points. Successful byte output operations shall not deliver invalid **UTF-8** sequences.

**Comment by FrankHB** [comment]
Does I/O imply side effects?

Probably for some UNIXy reasons, both ISO C and ISO C++ have some fundamental misconceptions to mix up interactions with external environment and conversion of data representations. I've filed a CWG issue to address the problem. Do not reproduce wrong designs.

**Comment by FirstLoveLife** [comment]
> I've filed a CWG issue to address the problem. Do not reproduce wrong designs.

any link?

**Comment by lhmouse** [comment]
Ideally either set of byte/text input/output functions will contain a unit function (such as `fgetc()` and `fgetwc()`) and a sequence function (such as `fwrite()`). Our `rocket::char_traits` already has I/O functions that do not distinguish null characters from the others, and operate `FILE*`s. Hence these bindings can be implemented i just a few hours.

**Comment by FrankHB** [comment]
@FirstLoveLife No. Mailed to CWG chair. No reply yet. (Reconstruction of the contents is under consideration.)

**Comment by FrankHB** [comment]
@lhmouse The primary problem is to make a clean design of the I/O framework. Features specific to FFI-based API (i.e. one-to-one mapped to `stdout`, etc.) is another problem factory. I don't see you can solve them altogether without having issues about bug-to-but compatibility to the underlying implementation.

Even if the ship has been sailed, there is still something wrong reserved to be avoided, e.g. global objects cannot be opt-out.

**Comment by expnkx** [comment]
That is why you should use my fast_io library.

**Comment by expnkx** [comment]
I provided all of your stuff.

**Comment by expnkx** [comment]
C++的I/O系统就是个灾难

**Comment by expnkx** [comment]
fgetc() is a mistake. EOF is a mistake. It should be replaced with input iterator model.

**Comment by lhmouse** [comment]
### `std.io`

`std.io.getc()`

        * Reads a UTF code point from standard input.

        * Returns the code point that has been read as an integer. If the
          end of input is encountered, `null` is returned.

        * Throws an exception if standard input is binary-oriented, or if
          a read error occurs.

`std.io.getln([limit])`

        * Reads a UTF-8 string from standard input, which is terminated
          by either a LF character or the end of input. The terminating
          LF is not included in the returned string. If `limit` is set,
          no more than this number of code points will be returned.

        * Returns the line that has been read as a string. If the end of
          input is encountered, `null` is returned.

        * Throws an exception if standard input is binary-oriented, or if
          a read error occurs, or if source data cannot be converted to a
          valid UTF code point sequence.

`std_io_putc(value)`

        * Writes a UTF-8 string to standard output. `value` may be either
          an integer representing a UTF code point or a UTF-8 string.

        * Returns the number of UTF code points that have been written.

        * Throws an exception if standard output is binary-oriented, or
          if source data cannot be converted to a valid UTF code point
          sequence, or if a write error occurs.

`std_io_putln(text)`

        * Writes a UTF-8 string to standard output, followed by a LF,
          which may flush the stream automatically. `text` may be either
          an integer representing a UTF code point or a UTF-8 string.

        * Returns the number of UTF code points that have been written.

        * Throws an exception if standard output is binary-oriented, or
          if source data cannot be converted to a valid UTF code point
          sequence, or if a write error occurs.

`std_io_read([limit])`

        * Reads a series of bytes from standard input. If `limit` is set,
          no more than this number of bytes will be read.

        * Returns the bytes that have been read as a string. If the end
          of input is encountered, `null` is returned.

        * Throws an exception if standard input is text-oriented, or if
          a read error occurs, or if source data cannot be converted to a
          valid UTF code point sequence.

`std_io_write(data)`

        * Writes a series of bytes to standard output. `value` shall be a
          byte string.

        * Returns the number of bytes that have been written.

        * Throws an exception if standard output is text-oriented, or if
          a write error occurs.

**Comment by expnkx** [comment]
> ### `std.io`
> `std.io.getc()`
> 
> * Reads a UTF code point from standard input.
> * Returns the code point that has been read as an integer. If the
>   end of input is encountered, `null` is returned.
> * Throws an exception if standard input is binary-oriented, or if
>   a read error occurs.
> 
> `std.io.getln([limit])`
> 
> * Reads a UTF-8 string from standard input, which is terminated
>   by either a LF character or the end of input. The terminating
>   LF is not included in the returned string. If `limit` is set,
>   no more than this number of code points will be returned.
> * Returns the line that has been read as a string. If the end of
>   input is encountered, `null` is returned.
> * Throws an exception if standard input is binary-oriented, or if
>   a read error occurs, or if source data cannot be converted to a
>   valid UTF code point sequence.
> 
> `std_io_putc(value)`
> 
> * Writes a UTF-8 string to standard output. `value` may be either
>   an integer representing a UTF code point or a UTF-8 string.
> * Returns the number of UTF code points that have been written.
> * Throws an exception if standard output is binary-oriented, or
>   if source data cannot be converted to a valid UTF code point
>   sequence, or if a write error occurs.
> 
> `std_io_putln(text)`
> 
> * Writes a UTF-8 string to standard output, followed by a LF,
>   which may flush the stream automatically. `text` may be either
>   an integer representing a UTF code point or a UTF-8 string.
> * Returns the number of UTF code points that have been written.
> * Throws an exception if standard output is binary-oriented, or
>   if source data cannot be converted to a valid UTF code point
>   sequence, or if a write error occurs.
> 
> `std_io_read([limit])`
> 
> * Reads a series of bytes from standard input. If `limit` is set,
>   no more than this number of bytes will be read.
> * Returns the bytes that have been read as a string. If the end
>   of input is encountered, `null` is returned.
> * Throws an exception if standard input is text-oriented, or if
>   a read error occurs, or if source data cannot be converted to a
>   valid UTF code point sequence.
> 
> `std_io_write(data)`
> 
> * Writes a series of bytes to standard output. `value` shall be a
>   byte string.
> * Returns the number of bytes that have been written.
> * Throws an exception if standard output is text-oriented, or if
>   a write error occurs.

This is a bad design. getc is a mistake. Are you going to provide ungetc?

put is even worse. There is no point for "fputc" to exist since you can always do better with write to array and then flush out.

**Comment by FrankHB** [comment]
The main problem is not about how to design concrete API. They are:

* Too many APIs are not qualified to be I/O. Traditionally, I/O is always *external* to the system (where the "system" generally means some abstraction machine semantics for a language, because even if there is a more fine-grained model, it can't have complete details about "external" states). Being I/O operations means there is absolutely no room to optimize such operations in effectiveless ("pure") ways. This makes conceptions like memory streams impossible to be naturally modeled in the system.
* I/O and non-I/O operations are mixed in a premature way (often too heavily). There indeed exist needs of high-level convenience interface to do such things for users, but there also exist too many naive ways of parallel derivations (e.g. edge-triggered vs. level-triggered in multiplexing, error codes vs. exceptions in error reporting, etc.) and neither one option can take the role of the core primitives to rule others out in a general-purpose language.
* High-level derivations of I/O APIs usually reflect little essence of I/O operations (that must be impure unconditionally). This implies the necessity of more fundamental primitives if you want all of high-level APIs able to be derived from the primitives portably and completely. Ignorance in this area is another stupidity in portable languages used as so-called "system" languages, albeit not that serious in high-level "glue" ones. However, this problem cannot be fixed by the latter without significant cons (e.g. code bloating and performance issues), either. 
* Explicit encoding schemes are evil being primitive under any I/O APIs. They are premature optimizations and make troubles for users who don't want to pay the overhead. Moreover, almost all operations are essentially *not* I/O, either (because they are not provided by hardware implementations which can not be decomposed in the system).
* Abstraction of streams with internal buffers provided by default are usually bad for lack of generality. Streams, in general, are data sources having potentially infinite volumes of values, by leverage of different evaluation strategies (notably, lazy evaluations). For genuine streams, this property should be more or less *default*. OTOH, genuine data sources implementing real I/O operations having no such guarantee. The semantic gap between these two tribe should be addressed in a proper design. Sadly, most languages have no sufficient support for this., and most I/O frameworks are simply designed without such issues in mind, leaving the problems to users. But users are not guided to provide saner derivations, either. The direct effect is many operations are totally not comparable even the orders of side effects are totally respected. This is an important (but not the only) reason that users found all kinds of stream in languages like C/C++ are not easy to use.

**Comment by FrankHB** [comment]
I won't criticize too much on `c` side of `fputc` besides the naming (that `c` should be `b` to fix the confusion of characters vs. bytes in traditional UNIXy designs), because byte-oriented vectorized data (so-called "arrays") are the de-facto transmission scheme across almost every systems. (Note that byte is good to be encoding-agnostic, while octet is 8-bit clean.) The problem in proposed APIs are the implicit objects as the data source. I see no reason to introduce so-called predefined I/O resources like `stdin`, `stdout`, `std::cin`, `std::cout`, etc. in a fresh design; and implicit resources are even worse esp. they are equally difficult to opt-out and providing less freedom on per-resource control.

**Comment by FrankHB** [comment]
An example of virtually sane design (not for the I/O module solely):

`std_get_system_environment` : Get an object of unspecified (noted as `sysenv` below) shared across the current runtime as the resource to provide capability of host environment resources.

`sysenv.get_default_input_device()` Get an object of input device type tied with underlying implementation-defined resource. In this implementation, it is one-to-one mapped to `stdin` in the standard C interface.

`sysenv.get_default_output_device()` Get an object of output device type tied with underlying implementation-defined resource. In this implementation, it is one-to-one mapped to `stdout` in the standard C interface.

...

(Limited specifications of I/O operations on the I/O devices come here.)

...

Rationale: I/O devices in the standard library only provide the basic APIs directly implemented in the native code which is external to this implementation. They provide a minimal set of necessary I/O operations used in the standard library. The can be extended by additional implementation-specific I/O operations. All I/O operations provided by I/O devices are unbuffered in this system, but the underlying native implementation may or may not have extra buffering not exposed to users in the language by design. High-level operations such as buffering, encoding, decoding and format conversions can be derived in the language by using these low level interface. Optionally, more low-level operations may or may not provided by extra native interface, depending on the implementation.

**Comment by lhmouse** [comment]
Moved to #94.
